openapi: 3.2.0
info:
  title: Shyft Customer Authentication > PhoneNumber API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Authentication > PhoneNumber
paths:
  /api/users:
    post:
      tags:
      - Authentication > PhoneNumber
      summary: PhoneNumber - Signup
      description: 'Description

        - - -

        - Sign up with fields listed at input section

        - API will generate and send a Login Code to user

        - Follow up with `confirm` API.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        referral_code| | | |

        acceptor_branch_id| | | |

        program_code| | | |

        referral_platform| | | |


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        first_name | | * | |

        last_name | | | |

        unconfirmed_phone_number | | * ||'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"api_user\": {\n    \"unconfirmed_phone_number\": \"18883839002\"\n    }\n}   \t\t "'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Tue, 20 Apr 2021 19:50:09 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Location:
              schema:
                type: string
                example: /
            ETag:
              schema:
                type: string
                example: W/"79be1d2c12138c5acfdc1836a3d92e97"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 547e3128-2de8-4663-9eb3-c2590fb90c47
            X-Runtime:
              schema:
                type: number
                example: '1.056196'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: PhoneNumber - Signup with ONLY phone number
                  value:
                    user:
                      _parent_object_id: null
                      id: 14294
                      active_org: 0
                      first_name: null
                      last_name: null
                      email: null
                      phone_number: null
                      gender: 0
                      chat_handle: e3a215ab27b5c6c958a3cd5a4f25dafb
                      user_group: 0
                      status: ''
                      push_settings_list:
                        shift_push:
                          label: Shift Notifications
                          type: boolean
                        schedule_push:
                          label: Schedule Notifications
                          type: boolean
                        community_push:
                          label: Community Notifications
                          type: boolean
                      push_settings_list_array:
                      - label: Shift Notifications
                        type: boolean
                        key: shift_push
                      - label: Schedule Notifications
                        type: boolean
                        key: schedule_push
                      - label: Community Notifications
                        type: boolean
                        key: community_push
                      thumb_url: null
                      gallery_url: null
                      full_url: null
                      current_position: null
                      current_user_privilege_id: null
                      current_is_approved: null
                      current_is_admin: null
                      all_push: true
                      shift_push: true
                      schedule_push: true
                      community_push: true
                      cfg_ewa_ok: null
                      locale: null
                      profile_image: null
                      recent_user_privilege: null
                example-1:
                  summary: PhoneNumber - Signup - with `sso_session_ids`
                  value:
                    user:
                      _parent_object_id: null
                      id: 9629
                      active_org: 0
                      first_name: John
                      last_name: Doe
                      email: null
                      phone_number: null
                      gender: 0
                      chat_handle: 3cc4ec7992af3e576322af368129901d
                      user_group: 0
                      status: ''
                      current_position: null
                      current_user_privilege_id: null
                      current_is_approved: null
                      profile_image: null
                      recent_user_privilege: null
                example-2:
                  summary: PhoneNumber - Signup - with profile image
                  value:
                    user:
                      _parent_object_id: null
                      id: 9628
                      active_org: 0
                      first_name: John
                      last_name: Doe
                      email: null
                      phone_number: null
                      gender: 0
                      chat_handle: 765629522ca204fdbde895943b9d9582
                      user_group: 0
                      status: ''
                      current_position: null
                      current_user_privilege_id: null
                      current_is_approved: null
                      profile_image:
                        thumb_url: https://coffeemobile.s3.amazonaws.com/images/thumb/8476_file.png?1542408637
                        gallery_url: https://coffeemobile.s3.amazonaws.com/images/gallery/8476_file.png?1542408637
                        full_url: https://coffeemobile.s3.amazonaws.com/images/full/8476_file.png?1542408637
                      recent_user_privilege: null
                example-3:
                  summary: PhoneNumber - Signup using PhoneNumber with email attached
                  value:
                    user:
                      _parent_object_id: null
                      id: 14063
                      active_org: 0
                      first_name: John
                      last_name: Doe
                      email: bin+nz1@myshyft.com
                      phone_number: null
                      gender: 0
                      chat_handle: 99db4cc977a5e9fa38bbcaeff352dd70
                      user_group: 0
                      status: ''
                      push_settings_list:
                        shift_push:
                          label: Shift Notifications
                          type: boolean
                        schedule_push:
                          label: Schedule Notifications
                          type: boolean
                        community_push:
                          label: Community Notifications
                          type: boolean
                      push_settings_list_array:
                      - label: Shift Notifications
                        type: boolean
                        key: shift_push
                      - label: Schedule Notifications
                        type: boolean
                        key: schedule_push
                      - label: Community Notifications
                        type: boolean
                        key: community_push
                      thumb_url: null
                      gallery_url: null
                      full_url: null
                      current_position: null
                      current_user_privilege_id: null
                      current_is_approved: null
                      current_is_admin: null
                      all_push: true
                      shift_push: true
                      schedule_push: true
                      community_push: true
                      cfg_ewa_ok: null
                      locale: null
                      profile_image: null
                      recent_user_privilege: null
      operationId: postApiUsers
      x-operation-id-source: derived
  /api/users/sign_in:
    post:
      tags:
      - Authentication > PhoneNumber
      summary: PhoneNumber - Sign in/Confirm
      description: 'Description

        - - -

        - Sign in user with SMS code

        - Get `Session-Token` or `Session-Uukey` from response headers, and use for further API calls.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        phone_number | | * | |

        sign_in_code | |* | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"api_user\": {\n    \"phone_number\": \"18883836001\",\n    \"sign_in_code\": \"9999\"\n  }\n}   "'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: query
        schema:
          type: integer
        example: '7'
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Location:
              schema:
                type: string
                example: /
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Session-Token:
              schema:
                type: integer
                example: '25764'
            Session-Uukey:
              schema:
                type: string
                example: 0ced24c0-cc32-418e-900e-1dea26e3c1cc
            access-token:
              schema:
                type: string
                example: dkEq2JQs5w0LXPPhGZUwhg
            token-type:
              schema:
                type: string
                example: Bearer
            client:
              schema:
                type: string
                example: bKC-6_hbF10ejlamKnDPkw
            expiry:
              schema:
                type: integer
                example: '1572547879'
            uid:
              schema:
                type: integer
                example: '18883836001'
            Phone-Number:
              schema:
                type: integer
                example: '18883836001'
            Auth-Category:
              schema:
                type: string
                example: phone_number
            Auth-Target:
              schema:
                type: integer
                example: '18883836001'
            Authorization:
              schema:
                type: string
                example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NjI1Iiwic2NwIjoiYXBpX3VzZXIiLCJhdWQiOm51bGwsImlhdCI6MTU0MTA5ODI3OSwiZXhwIjoxNTQxMTAxODc5LCJqdGkiOiIwMmFmYTRhMS05ZGJiLTQwMGQtYTc2MS1iNjRiMGRiZDJkODMifQ.l9sRtAAVmgJj03F9IzzEXtHo8K8UGYRWh27fdhJ1oCQ
            ETag:
              schema:
                type: string
                example: W/"9a7a5b72b492fe1b4e13268da2aaf631"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=N1BRTEY2dlNuTGZoVzZnVHNuSS9BQVVvRytEeld1WUQxN2hOVnFpcHVsWUwveExNU0ozU2hhOFBrTmttei80T1gvMUt6aWtONzNJblIreFNSY0NCZ2c9PS0tT0dVQ2dOZy9IWmNQZEczNDBoQk1PUT09--6123dd08017535690c0617f94304699c55d26c28; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: Bin%27s+Local+Server
            X-Request-Id:
              schema:
                type: string
                example: 3a9b263b-6772-474e-8a9d-bbc97b85798c
            X-Runtime:
              schema:
                type: number
                example: '0.448973'
            Vary:
              schema:
                type: string
                example: Origin
            Connection:
              schema:
                type: string
                example: close
            Server:
              schema:
                type: string
                example: thin 1.5.1 codename Straight Razor
          content:
            application/json:
              schema:
                type: object
              example:
                user:
                  _parent_object_id: null
                  id: 9625
                  active_org: 0
                  first_name: John
                  last_name: Doe
                  email: null
                  phone_number: '18883836001'
                  gender: 0
                  chat_handle: 911bf630a47c543b70303b3a42400f14
                  user_group: 0
                  status: ''
                  profile_image: null
                  recent_user_privilege: null
      operationId: postApiUsersSignIn
      x-operation-id-source: derived
  /api/code_auth/18885555555:
    get:
      tags:
      - Authentication > PhoneNumber
      summary: PhoneNumber - Get SMS Code
      description: 'Description

        - - -

        - Resend confirmation code if user did not get previous one


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        confirm| true | * | Must set it be true


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        unconfirmed_phone_number | | * | |

        sign_in_code | |* | |'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: confirm
        in: query
        schema:
          type: boolean
        description: 'when first time login, target on unconfirmed account

          '
        example: 'true'
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Content-Type:
              schema:
                type: string
                example: application/json
            Cache-Control:
              schema:
                type: string
                example: no-cache
            X-Request-Id:
              schema:
                type: string
                example: 578b6f22-0418-42e8-ad45-23dfbc607251
            X-Runtime:
              schema:
                type: number
                example: '0.124879'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Content-Encoding:
              schema:
                type: string
                example: gzip
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              example: {}
      operationId: getApiCodeAuth18885555555
      x-operation-id-source: derived
  /api/users/super_login:
    get:
      tags:
      - Authentication > PhoneNumber
      summary: PhoneNumber - SuperLogin
      description: 'Description

        - - -

        - Login as a God build

        - Get `Session-Token` or `Session-Uukey` from response headers, and use for further API calls.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        login | | * | | phone_number or email


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---

        God-Key | | * | |


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: God-Key
        in: header
        schema:
          type: string
        example: '{{god_key}}'
      - name: login
        in: query
        schema:
          type: integer
        example: '18883836001'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiUsersSuperLogin
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
