openapi: 3.2.0
info:
  title: Shyft Customer Customer > Departments > Memberships API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Departments > Memberships
paths:
  /api/customer/user_role/department_memberships/mine:
    get:
      tags:
      - Customer > Departments > Memberships
      summary: get mine department memberships
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: query
        schema:
          type: integer
        example: '2806'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 05:16:30 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"27b6ff4c59228ad5920b23113d9aa95c"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=SENSWVVhcmFXbnFpUm1FYVlkUDZQMm5pSDhhWHowRXlYWkxJN1VpcWNwaWtBdkZSbVVMNmJXQU1DU3Z6UG1uOTc2bVZhWGFrSWxlWnE1bnVHeE10anc9PS0tdWFLNEw2UE51T3UyVEhlYXQ4TVZUdz09--72fadd74a3019184cfbb4820b8b25e503f24be12; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: dc731dae-a87d-4f2e-9f83-60f9576c0fc7
            X-Runtime:
              schema:
                type: number
                example: '3.560532'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: get mine department memberships
                  value:
                    department_memberships:
                    - _parent_object_id: null
                      id: 10
                      department_id: 1
                      user_privilege_id: 21574
                      user_id: 14815
                      is_main: false
                    meta:
                      pagination:
                        current_page: 1
                        per_page: 25
                example-1:
                  summary: get mine department memberships - with location filter
                  value:
                    department_memberships:
                    - _parent_object_id: null
                      id: 10
                      department_id: 1
                      location_id: 2806
                      user_privilege_id: 21574
                      user_id: 14815
                      is_main: false
                    meta:
                      pagination:
                        current_page: 1
                        per_page: 25
      operationId: getApiCustomerUserRoleDepartmentMembershipsMine
      x-operation-id-source: derived
  /api/customer/user_role/department_memberships:
    post:
      tags:
      - Customer > Departments > Memberships
      summary: create a new department membership
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"department_membership\": {\n        \"user_privilege_id\": 21189,\n        \"department_id\": 1, \n        \"is_main\": true\n    }\n}\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 20:42:22 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"86dddc9d9a9adff6743787ec3ebdbef0"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=YkU2dm5wVExNZmhQUUV5b1pFRWlXamVWM0t2OW5yckwvSy9UazJWZWNmWlJhQVkrRGJLczNyS3dJaGhPOE9ySzZrMGdJR1YxSWNqdTR6azdheVQwc0E9PS0tRlJ4dlhvUmZJMVZCRy82dEp2VFY3Zz09--18d99082d353d1e1c8c8712908b76a8340b5f37a; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: d30ce28d-8f6e-48aa-b24a-8fc248f6333a
            X-Runtime:
              schema:
                type: number
                example: '0.403977'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                department_membership:
                  _parent_object_id: null
                  id: 11
                  department_id: 1
                  location_id: 2806
                  user_privilege_id: 21189
                  user_id: 14526
                  is_main: true
      operationId: postApiCustomerUserRoleDepartmentMemberships
      x-operation-id-source: derived
  /api/customer/user_role/department_memberships/10:
    put:
      tags:
      - Customer > Departments > Memberships
      summary: udpate a department membership
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"department_membership\": {\n        \"is_main\": true\n    }\n}\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 20:58:03 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=QzBoR3ZRRERjU1BjbE1lRk40MXJXSDlnaDF6dHhBbnExVjdUODl3RzNwb1IwNm9Ua01ieU8yTzVvRzZrMEFjNkxIc3p5c3NzTTJVOXVia2dlZ3ZNTGc9PS0tMjBQNFVYcm9wM0phZ09wSktQRVk3dz09--f82860ed7ce46735676189e5de7a6a57fecaf7fe; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: e070ff33-3337-49e6-a10e-67aecd322e3e
            X-Runtime:
              schema:
                type: number
                example: '0.433338'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
      operationId: putApiCustomerUserRoleDepartmentMemberships10
      x-operation-id-source: derived
    delete:
      tags:
      - Customer > Departments > Memberships
      summary: delete a department membership
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 21:07:32 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ZUJSUEI4akd6Qnl5MFBNMnJtV0ZiK2hLREtWb3daM2UycWJjTDF6UGJ0NDBIU3Y1VlNLNnVSUWdWMDdjY25TcTZ1b0FmOVJFYm5uUjMycE1iQmIyU1E9PS0tR1V3Z21WRzlMclJrcGxIaFE0aEIydz09--b861167f4bdc17562d3b708e44c70b47193bfdcd; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 02c8e167-4ae6-4e73-bf33-bd016811d663
            X-Runtime:
              schema:
                type: number
                example: '4.716156'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
      operationId: deleteApiCustomerUserRoleDepartmentMemberships10
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
