openapi: 3.2.0
info:
  title: Shyft Customer Customer > Availabilities > admin_role >…
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Availabilities > admin_role > request
paths:
  /api/customer/admin_role/locations/{location_id}/availability_requests/current:
    get:
      tags:
      - Customer > Availabilities > admin_role > request
      summary: '[availability request] get curent open one for admin'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 'OK '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example:
                availability_requests:
                - id: 12
                  user_id: 9046
                  location_id: 2159
                  is_active: true
                  closed: false
                  notes: please submit your new availability
                  availabilities:
                  - id: 69
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 70
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 71
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 72
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 73
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 74
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 75
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 76
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
                  - id: 77
                    status: pending
                    notes: null
                    user_id: 9046
                    location_id: 2159
                    availability_request_id: 12
                    sunday:
                      start_at: 00:00
                      end_at: null
                    monday:
                      start_at: '10:00'
                      end_at: '12:00'
                    tuesday:
                      start_at: null
                      end_at: '12:00'
                    wednesday:
                      start_at: null
                      end_at: null
                    thursday:
                      start_at: null
                      end_at: null
                    friday:
                      start_at: null
                      end_at: null
                    saturday:
                      start_at: null
                      end_at: null
      operationId: getApiCustomerAdminRoleLocationsByLocationIdAvailabilityRequestsCurrent
      x-operation-id-source: derived
  /api/customer/admin_role/locations/{location_id}/availability_requests/56:
    get:
      tags:
      - Customer > Availabilities > admin_role > request
      summary: '[availability request] get specfic request'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 'OK '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example:
                availability_request:
                  id: 15
                  user_id: 9046
                  location_id: 2159
                  is_active: true
                  closed: false
                  notes: please submit your new availability
                  users_count: 5
                  submitters_count: 0
                  availabilities: []
      operationId: getApiCustomerAdminRoleLocationsByLocationIdAvailabilityRequests56
      x-operation-id-source: derived
    put:
      tags:
      - Customer > Availabilities > admin_role > request
      summary: '[availability request] update request or close it'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"availability_request\": {\n  \t\"closed\": \"true\"\n  }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '204':
          description: 'No Content '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            text/plain:
              schema:
                type: string
              example: ''
      operationId: putApiCustomerAdminRoleLocationsByLocationIdAvailabilityRequests56
      x-operation-id-source: derived
  /api/customer/admin_role/locations/{location_id}/availability_requests:
    post:
      tags:
      - Customer > Availabilities > admin_role > request
      summary: '[availability request] create request'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"availability_request\": {\n  \t\"notes\": \"please submit your new availability\"\n  }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '201':
          description: 'Created '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example:
                availability_request:
                  id: 15
                  user_id: 9046
                  location_id: 2159
                  is_active: true
                  closed: false
                  notes: please submit your new availability
                  availabilities: []
        '422':
          description: 'Unprocessable Entity '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  location_id:
                  - can only have one open request for each location at same time
      operationId: postApiCustomerAdminRoleLocationsByLocationIdAvailabilityRequests
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
