openapi: 3.2.0
info:
  title: Shyft Customer Customer > Uploader API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Uploader
paths:
  /api/customer/uploader/file:
    post:
      tags:
      - Customer > Uploader
      summary: upload a file
      description: 'Description

        - - -

        - upload a file: PDF


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        * Please use `form-data`


        Attribute | Values | R |Description

        --- | --- | --- | ---

        file | | * | file type blob'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"849b99df7f29e9b185233171f5db90ee"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ZzV2VUFtYitjbXQ1M2JBTVNmdlpRdHNnUmlXNUkzRExxamhPdGxsMFpGTFJESnBEbzVTZFlwU0xBODU3Tml6QWRVbzkzYmhLeTQ3S1NtOWpwWFFzcHc9PS0tUU9mS2lyZk9raW5QRDNYd01VOHZ3dz09--fdbe7b667eff98ccb80012e285084bb692818565; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 876d1928-59f3-4840-b39e-e7e3c6aaf43e
            X-Runtime:
              schema:
                type: number
                example: '1.976292'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: upload a file - audio
                  value:
                    blob:
                      _parent_object_id: null
                      id: 126
                      content_type: audio/mpeg
                      service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/QjsCfPUivrmw22fKqi2eKW9H?sp=r&sv=2016-05-31&se=2020-06-01T19%3A56%3A01Z&rscd=attachment%3B+filename%3D%22sample.mp3%22%3B+filename*%3DUTF-8%27%27sample.mp3&rsct=audio%2Fmpeg&sr=b&sig=uuveugkh2943MPPo7Qne07up%2FgmQGre27U2xNlZuxc0%3D
                      preview_service_url: null
                      filename: sample.mp3
                      byte_size: 764176
                example-1:
                  summary: upload a file - pdf
                  value:
                    blob:
                      _parent_object_id: null
                      id: 35
                      content_type: application/pdf
                      service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/MpwPmC5LVhzg6xRdkemJAy3e?sp=r&sv=2016-05-31&se=2020-05-29T22%3A14%3A58Z&rscd=inline%3B+filename%3D%22sample.pdf%22%3B+filename*%3DUTF-8%27%27sample.pdf&rsct=application%2Fpdf&sr=b&sig=0h2pk02Riuzr9c0Wli1KsI4B7pOABJoVu8aVXsH%2FoQc%3D
                      preview_service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/variants/RnEvJCGTWb4pBkhQu4Le4ktX/a0ec96f9aeb9d604b7135a8679668c2926c2f2937213c3559f3a7ce8423393d2?sp=r&sv=2016-05-31&se=2020-05-29T22%3A15%3A00Z&rscd=inline%3B+filename%3D%22sample.png%22%3B+filename*%3DUTF-8%27%27sample.png&rsct=image%2Fpng&sr=b&sig=tfIQ0iTK5zYCqrW3dYaFa6Yhtrn%2BX0UaxmcIUtVw%2B%2BA%3D
                      filename: sample.pdf
                      byte_size: 3028
                example-2:
                  summary: upload a file -video
                  value:
                    blob:
                      _parent_object_id: null
                      id: 275
                      content_type: video/mp4
                      service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/FzSVZyQQEgJaooedmfWjACYu?sp=r&sv=2016-05-31&se=2020-06-03T22%3A32%3A11Z&rscd=attachment%3B+filename%3D%22sample.mp4%22%3B+filename*%3DUTF-8%27%27sample.mp4&rsct=video%2Fmp4&sr=b&sig=7kbjDyqK7UciFncS7NULH0sy3dFhmPyqOiJwntYm7HM%3D
                      preview_service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/variants/UyGaFPmzgMWUcvwLuWoFFP4Y/a0ec96f9aeb9d604b7135a8679668c2926c2f2937213c3559f3a7ce8423393d2?sp=r&sv=2016-05-31&se=2020-06-03T22%3A32%3A12Z&rscd=inline%3B+filename%3D%22sample.png%22%3B+filename*%3DUTF-8%27%27sample.png&rsct=image%2Fpng&sr=b&sig=AqTdEWfQS5uWy1gJN2CKEzAfFEM5de8ATn09sYeQkww%3D
                      filename: sample.mp4
                      byte_size: 1055736
                      blob_url: http://sp1-service.myshyft.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE1CIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2fdbac200c68cdb2dfc6d2a618e2e240243dc60b/sample.mp4
                      preview_blob_url: http://sp1-service.myshyft.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFFCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05015ed49ecaad1de9e6a0ac11f2dd5cee383aa6/sample.png
                example-3:
                  summary: upload a file - image
                  value:
                    blob:
                      _parent_object_id: null
                      id: 1314
                      content_type: image/jpeg
                      service_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/ZTPDDJ8aWSzLeJWccgUWvYsc?sp=r&sv=2016-05-31&se=2021-04-20T21%3A56%3A24Z&rscd=inline%3B+filename%3D%22sample.jpeg%22%3B+filename*%3DUTF-8%27%27sample.jpeg&rsct=image%2Fjpeg&sr=b&sig=%2BNP0GaEarIHE%2BmJcAPRU3ypi2vCHdPVgfkoA%2FCH3G%2Bs%3D
                      filename: sample.jpeg
                      byte_size: 32994
                      blob_url: https://test-service.myshyft.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--109658607da86322831edb0b946862a8819b66cb/sample.jpeg
                      preview_blob_url: null
      operationId: postApiCustomerUploaderFile
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
