openapi: 3.2.0
info:
  title: Shyft Customer Customer > EWA API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > EWA
  description: 'Ojbect Serializer:


    [EWA Account Serializer]


    Attribute | Values | R | Description

    --- | --- | --- | ---

    id | | |

    tos_yes | | | Indciate if user has accepted the TOS by going through all pages.'
paths:
  /api/customer/user_role/ewa/ewa_accounts/my_account:
    get:
      tags:
      - Customer > EWA
      summary: '[ewa_account] get or create my EWA account'
      description: 'Description

        - - -

        - This is the first API call when user choose to use EWA by clicking the function button.

        - It will find the current user''s existing EWA account and return its profile.

        - It will create a new basic EWA account for current user if not found one, and return its profile


        If got `tos_yes=false`, front-end want to present these TOS pages again.

        If got no `active_bank_account`, front-end want to present the bacnk account linking page


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [EWA Account Serializer]'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"7454061f2b2878f16873587f2716b90e"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ZVR1d3g1cXFOaCtLZkJQR0FCWlNIQWdIS1NzN3c4RkpoWll0b08wTGcrSU1sUW43OUJaYkFja2FZTVJRejlVZGhCWEF3b3d1VEhZNGNVOVlLYUliZVE9PS0ta2hnY1ljUDVjTzhQSFBhRmlOL0xpdz09--8bfd3743ff86cefa6b6480e7b6cef744e9c7c8ad; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: e8ca009c-3c0e-4417-8965-15e6ebfdd206
            X-Runtime:
              schema:
                type: number
                example: '20.730608'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_account:
                  _parent_object_id: null
                  id: 1
                  tos_yes: true
                  is_active: true
                  ewa_score: null
                  ewa_balance_cents: -400
                  ewa_maximal: null
                  ewa_status: ewa_not_applicable_user
                  active_bank_account:
                    _parent_object_id: 1
                    account_owner_name: Plaid Checking
                    bank_name: US Bank
                    bank_code: null
                    description: Plaid Gold Standard 0% Interest Checking
                    is_active: true
      operationId: getApiCustomerUserRoleEwaEwaAccountsMyAccount
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_accounts/request_email_confirmation:
    get:
      tags:
      - Customer > EWA
      summary: '[ewa_account] request email confirmation'
      description: 'Description

        - - -

        - Apply to use EWA function by requesting a confirmation by email


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        unconfirmed_email | string | * | The email to receive confirmation code


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [EWA Account Serializer]'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: unconfirmed_email
        in: query
        schema:
          type: string
        example: bin%2Bewa@myshyft.com
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"6e9067066cf31b2cb28986215e4a5b33"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ZGR1M3M2SHdEb0pYL0VCWkFUM0RxelRDNENLY3RaQlNpQnZXSlZKTUJZT0gvaXo4VzJnY0VQYjNQYXMzeUowMTA5Mm9TT2ZQVFVaa2ZZOTZXTGQwR3c9PS0tbUFiOHZ0RzZ0c2d0SS9uZDhnUTVXUT09--f4946504823c25fe4d0eb8def0c1b96d5dbc4dc0; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: f57c4f37-1d00-4041-8d9e-947a29523720
            X-Runtime:
              schema:
                type: number
                example: '3.381592'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_account:
                  _parent_object_id: null
                  id: 1
                  tos_yes: true
                  is_active: true
                  ewa_score: null
                  ewa_balance_cents: 300
                  ewa_maximal_cents: null
                  ewa_status: ewa_has_balance
                  next_payback_date: null
                  email: null
                  is_confirmation_requested: true
                  is_confirmed: false
                  active_bank_account:
                    _parent_object_id: 1
                    account_owner_name: Plaid Checking
                    bank_name: US Bank
                    bank_code: null
                    description: Plaid Gold Standard 0% Interest Checking
                    is_active: true
                    ewa_maximal_cents: null
                    next_payback_date: null
                    maximal_payback_date: null
      operationId: getApiCustomerUserRoleEwaEwaAccountsRequestEmailConfirmation
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_accounts/borrow_estimate:
    get:
      tags:
      - Customer > EWA
      summary: '[ewa_account] get the estimation of capability of borrowing'
      description: 'Description

        - - -

        - Apply to use EWA function by requesting a confirmation by email


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        unconfirmed_email | string | * | The email to receive confirmation code


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [EWA Account Serializer]'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleEwaEwaAccountsBorrowEstimate
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_accounts/confirm_email_with_code:
    get:
      tags:
      - Customer > EWA
      summary: '[ewa_account] confirm EWA account''s email with code'
      description: 'Description

        - - -

        - Apply to use EWA function by requesting a confirmation by email


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        unconfirmed_email | string | * | The email to receive confirmation code


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [EWA Account Serializer]'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: confirmation_code
        in: query
        schema:
          type: integer
        example: '9999'
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"39648b13d4d79c68b207d5618a628db4"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=NmpBTXZsSmh2ZmlBOHVSNy9FTjdka0ZOWjRRUEVTSDNqTFBzeGtRYkVqdnBmZEJ3ZTdUNHViU0N5Vm56azZGSEkxT3JUVlRoSVJVRTdtWU1jMVhrcGc9PS0tbkVSSk9wVWdFbk9JWERnNTdSMnZjdz09--6626ab9bd8e1f7d6d8f986a7b09fa0e1738368bc; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 4e5c69e1-93d7-41e6-9877-d0dfea208c58
            X-Runtime:
              schema:
                type: number
                example: '3.081910'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_account:
                  _parent_object_id: null
                  id: 1
                  tos_yes: true
                  is_active: true
                  ewa_score: null
                  ewa_balance_cents: 300
                  ewa_maximal_cents: null
                  ewa_status: ewa_has_balance
                  next_payback_date: null
                  email: bin+ewa@myshyft.com
                  is_confirmation_requested: false
                  is_confirmed: true
                  active_bank_account:
                    _parent_object_id: 1
                    account_owner_name: Plaid Checking
                    bank_name: US Bank
                    bank_code: null
                    description: Plaid Gold Standard 0% Interest Checking
                    is_active: true
                    ewa_maximal_cents: null
                    next_payback_date: null
                    maximal_payback_date: null
        '400':
          description: Bad Request
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=dWZBNDYrRVNCZXU0STNpR2MyTkRLZXFIbmVFVitPdXBka1U1aytMeHBDWnRuN0lhRzVneDRvUnhOSGpLU3ZPay9OSXhqcGpVa1U4SDIwTVVZa3NCcUE9PS0tbkozSHdWOWg2THVnaHZJdW9BTW9KQT09--630b475879160686902c6f5a2250482003e55630; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 338294f0-e44a-4617-a36c-d50f008ff273
            X-Runtime:
              schema:
                type: number
                example: '21.702526'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  confirmation_code:
                  - invalid code.
      operationId: getApiCustomerUserRoleEwaEwaAccountsConfirmEmailWithCode
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_accounts/{ewa_account_id}:
    put:
      tags:
      - Customer > EWA
      summary: '[ewa_account] confirm the TOS agreement'
      description: 'Description

        - - -

        - Once user went through all TOS pages, mark it.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        tos_yes | boolean | * |


        Output

        - - -

        [EWA Account Serializer]'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\t\"ewa_account\": {\n\t\t\"tos_yes\": true\n\t}\t\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[put_return_resource]
        in: query
        schema:
          type: boolean
        example: 'true'
      - name: ewa_account_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"8a268f25cb24149c0c300b4b492defd7"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=VVBmaW1pVklTbXRxWjY5bmdkSUg3L2lmRFYxK0RPWlRRSkhBVEJTQW5Tc0ZuMWtQWnJUNTBFVWtyOWNxbEZ2QXM3aHBoTHNLZWROVS9DYTBzUU1SRlE9PS0tR1M4V0ZGYWIraGlGVFltUG5LVHNmQT09--5fa013bc3df6d04ab1b5d0a5ae91343db0411599; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 22bde3ef-7b80-4c61-985e-aac3b3754c0c
            X-Runtime:
              schema:
                type: number
                example: '0.086246'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_account:
                  _parent_object_id: null
                  id: 1
                  tos_yes: true
                  is_active: true
                  ewa_score: null
                  ewa_balance: '-100.0'
                  ewa_maximal: null
                  active_bank_account:
                    _parent_object_id: 1
                    account_owner_name: Bin Li
                    bank_name: Fake Bank
                    bank_code: FAKE_BANK_CODE
                    description: null
                    is_active: true
      operationId: putApiCustomerUserRoleEwaEwaAccountsByEwaAccountId
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_transactions/borrow:
    post:
      tags:
      - Customer > EWA
      summary: '[ewa_transaction] borrow money'
      description: 'Description

        - - -

        - Call this API when customer want borrow money from Shyft


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        amount_cents| integer | * | in cents

        due_at | date | | customer selected payback date


        Output

        - - -


        [EWA Transaction Serializer]'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"ewa_transaction\": {  \n\t\t\"amount_cents\": 100,\n\t\t\"due_at\": \"2020-03-01\"\n\t}\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"7e9929e5a92ca1944ad4ecb6d7fb29e8"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=WGxJRExIVGNQZDRNTHZCeEFjaU14Q1hqd29Mck05Vm1UakRhckJpemhSZDNIaGdSVURhNUVHeEoyem14RktHeDJaQ1grU2ZNTEdQM043Zm1pWnJQVWc9PS0tdkwxZjFQelBjWVBmTFhjNXcreW51QT09--8b1fe2624aebb2751ae548e4f6e19dcd82347234; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 213f18e6-f02b-4d64-8b6c-a7639b02709e
            X-Runtime:
              schema:
                type: number
                example: '19.711830'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_transaction:
                  _parent_object_id: null
                  amount_cents: 100
                  amount_currency: USD
                  source_ewa_balance: 600
                  transaction_type: borrow
                  due_at: '2020-03-01'
      operationId: postApiCustomerUserRoleEwaEwaTransactionsBorrow
      x-operation-id-source: derived
  /api/customer/user_role/ewa/ewa_transactions/payback:
    post:
      tags:
      - Customer > EWA
      summary: '[ewa_transaction] return money'
      description: 'Description

        - - -

        - Call this API when customer want return money from Shyft


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        amount_cents| integer | * | in cents


        Output

        - - -

        [EWA Transaction Serializer]'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"ewa_transaction\": {  \n\t\t\"amount_cents\": 100\n\t}\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"15102346a360f0201ec43481a49fc7e7"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=QTMwNjlPYUNaNkdtdERCZTFzdGtZSXRwS0xGdXJob1JkRHJhOHBQWkR2aXNXVmNBY2N3NS9DcE1RdWpsL3R0OGppdjh0Mm9SUTd1c1lmTXpZVGRpakE9PS0tUzgwek5CN1NySytqVXlXRFZ1Y0JFdz09--4720b9a87a68f5381a41feed518084f4f00aa754; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: c3e25dda-544f-4937-b5a3-6c0e6b38c8a2
            X-Runtime:
              schema:
                type: number
                example: '0.127562'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                ewa_transaction:
                  _parent_object_id: null
                  amount_cents: -100
                  amount_currency: USD
                  ewa_balance: '-300.0'
                  transaction_type: payback
      operationId: postApiCustomerUserRoleEwaEwaTransactionsPayback
      x-operation-id-source: derived
  /api/customer/user_role/ewa/bank_accounts/add_account:
    post:
      tags:
      - Customer > EWA
      summary: '[bank_account] create and active bank_account'
      description: 'Description

        - - -

        - Add a new bank account to current user''s EWA account

        - Will deactive all other bank accounts if new one added

        -


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        public_token | string | * | the token got from Plaid


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        bank_name | string | * | the bank name got from Plaid


        Output

        - - -


        [Bank Account Serializer]'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\t\"bank_account\": {\n\t\t\"bank_name\": \"US Bank\"\n\t}\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: public_token
        in: query
        schema:
          type: string
        example: public-sandbox-5df51fa7-25e5-4c1f-ba0b-87705ccbfc1b
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"5ad087b5ade9216cd3239ebbb62c3644"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=UXZOWkZLb2o2UlNubjgyTDc3RVlYUElJazlmK1NWTkNSZmpwY0dQWHlHMVduY0l1N25tV2E5aGlzS1cwSnNSZWJmY2I3d3BIc213b3dYNzhHM3F2T3c9PS0tcmdoOENZM2lrdUM3MWhCV3pvREQrQT09--909aa3fbdbb36d5dac3c6396a7903193fe0996a6; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: f37bef60-6ad6-4ec1-8783-7979e20ab080
            X-Runtime:
              schema:
                type: number
                example: '8.522391'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                bank_account:
                  _parent_object_id: null
                  account_owner_name: Plaid Checking
                  bank_name: US Bank
                  bank_code: null
                  description: Plaid Gold Standard 0% Interest Checking
                  is_active: true
                  ewa_maximal_cents: 100
                  next_payback_date: '2020-03-06T01:35:21.740Z'
                  maximal_payback_date: '2020-03-20T01:35:21.740Z'
      operationId: postApiCustomerUserRoleEwaBankAccountsAddAccount
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
