openapi: 3.2.0
info:
  title: Shyft Customer Customer > Departments API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Departments
paths:
  /api/customer/user_role/locations/2806/inner_departments:
    get:
      tags:
      - Customer > Departments
      summary: get location inner departments
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 03:23:00 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"1155cb1a6df8ee1e83400febb3f2e30f"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=allLMCtQSDQyVUpmUGtVUjNFUzZlTVBoZmtLOHhLTmhtNmFFUFFsZWM4dFl2dUlKVElCVkF3a0RPUjJ2NmNJMElLTzN5eWZ2bmhiQ3ZWMm5jOUpYMnc9PS0tSkp0aUU4c2t3ay9DK3BHY3N1OS80QT09--82153287fea5bc9f0e12d6e6b31b33bae83f08a7; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: fbc54ba3-4ffe-45ed-b040-0d31bd6949a9
            X-Runtime:
              schema:
                type: number
                example: '1.300053'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                departments:
                - _parent_object_id: null
                  id: 1
                  location_id: 2806
                  name: Sample Department
                  description: null
      operationId: getApiCustomerUserRoleLocations2806InnerDepartments
      x-operation-id-source: derived
  /api/customer/user_role/departments/mine:
    get:
      tags:
      - Customer > Departments
      summary: get mine departments
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Mon, 19 Sep 2022 06:13:13 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"5c46867ece13ab7e25b71012c0a55cc9"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=S1dFSFRZMnNKMkc4aER0Qjgzbm55NjNHcVZOd2h2eGZ6azFnVkc0ZUVDT2Zwb0pjcjVFUEc1TlV3TGU4c2NaMjkrbjAyY0RGWEh4ck1RWGtIYjVqM0E9PS0tS3JGT1NmSHkrZnZlZ0k5TlA4eHkrUT09--2cb857ae1ccb27b9803bae64697ea7b5b0cd33cd; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 7277b3dd-e3de-43aa-a790-26261567e591
            X-Runtime:
              schema:
                type: number
                example: '0.425395'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                departments:
                - _parent_object_id: null
                  id: 1
                  location_id: 2806
                  name: Sample Department 2
                  description: null
                  users_count: 5
                  user_ids:
                  - 14196
                  - 14199
                  - 14206
                  - 7613
                  - 14815
                meta:
                  pagination:
                    current_page: 1
                    per_page: 25
      operationId: getApiCustomerUserRoleDepartmentsMine
      x-operation-id-source: derived
  /api/customer/user_role/departments:
    post:
      tags:
      - Customer > Departments
      summary: create a new department
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\"department\": {\n    \"location_id\": 2806,\n    \"name\": \"Sample Department\",\n    \"description\": \"Test Sample Department\"\n    }\n}\t\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 22:56:38 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"2431117b344f7e250ca30b7b0e36678a"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=NVcvQXN6ZWdRV0h5ckxqVGF5M0NPK21Bekl2ck9PdnRJYkhnaURCQ3FFV2wybDJaOUNzVU84bE9zYll0SGZrRU1uMVFZNEIyT2tkNDJ4OHZybW1Pb0E9PS0tWXZoM0FxUld6TzYvUmpmUjVNWlR2Zz09--30cc94175768c6d1e76558c5f819a45bc812641d; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: f9e1591b-aa50-4f0c-9bc8-097595cdfa82
            X-Runtime:
              schema:
                type: number
                example: '0.408060'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                department:
                  _parent_object_id: null
                  id: 2
                  location_id: 2806
                  name: Sample Department
                  description: Test Sample Department
                  users_count: 0
      operationId: postApiCustomerUserRoleDepartments
      x-operation-id-source: derived
  /api/customer/user_role/departments/1:
    put:
      tags:
      - Customer > Departments
      summary: update a new department
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\"department\": {\n    \"name\": \"Sample Department 2\"\n    }\n}\t\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 23:00:02 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=OHJtMlN0U3N5cGRzYStSTmtXZjZTVkU2WGNhWWxRbEdldFlybGo0bkExVUFYbEUrd0FFVWFIek50cnpBK0tDTVQ1OVAraGdLRGdTNGJBMmlJNzh4UUE9PS0tMExaQ2VZd3N2Vm9KUFM3YVo0NHBydz09--07e7dd47e69f99b4fb2076a29f591f55600d6778; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 1dd2554f-3735-41f7-9cac-1dfbcb93af52
            X-Runtime:
              schema:
                type: number
                example: '0.235478'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
      operationId: putApiCustomerUserRoleDepartments1
      x-operation-id-source: derived
  /api/customer/user_role/departments/1/assign_users:
    put:
      tags:
      - Customer > Departments
      summary: assign a department users
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"department\": {\n        \"remove_user_ids\": [ 14794, 14992, 14474, 14974]\n    }\n}\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[put_return_resource]
        in: query
        schema:
          type: boolean
        example: 'true'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Mon, 19 Sep 2022 04:58:37 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"ef0a0816122ded71c6a6db9a2e42c1a2"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ejlyWWdLU3BYa05JelRFVmhqWFdSbU1aWGx3cktZdEFTMUMrSDJUM1NtaGtUYll5cC8wWnYvdi81K1Vya3F3YTVTdmhUTHdkNzdzd0JEY0JtVVh6Vmc9PS0tY0tLNFp1eFhjZ2JaMGhKdDFCdkp6dz09--00c4c9d0893f2b78a3e8d946a3f953a69861f995; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 45659acd-0efc-46d9-b139-03959889f113
            X-Runtime:
              schema:
                type: number
                example: '0.417984'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: assign a department users - add
                  value:
                    department:
                      _parent_object_id: null
                      id: 1
                      location_id: 2806
                      name: Sample Department 2
                      description: null
                      users_count: 8
                example-1:
                  summary: assign a department users - remove
                  value:
                    department:
                      _parent_object_id: null
                      id: 1
                      location_id: 2806
                      name: Sample Department 2
                      description: null
                      users_count: 4
      operationId: putApiCustomerUserRoleDepartments1AssignUsers
      x-operation-id-source: derived
  /api/customer/user_role/departments/2:
    delete:
      tags:
      - Customer > Departments
      summary: delete a department
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 23:05:23 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=TEFERlFTcHhsdjJ6TlhRZ2xhVzFOSVBkZlgzdFROMU13Qkw1V0VXN1BRcXUxSXY0WFpRRGZOM2ptWkFXVjJXZFdvZUJldGtYTE14WWVEUlJLc2ZCZlE9PS0tNDhzWEFBYmlQZmdGNXhsSHhWYWI2Zz09--8cea5ae86d841368b618c11c57fe7cb77191f8c8; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 692f08f0-de64-4923-8bec-b893830928fc
            X-Runtime:
              schema:
                type: number
                example: '1.050138'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
      operationId: deleteApiCustomerUserRoleDepartments2
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
